# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: National Institute of Informatics.
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: nbsearch
mimetype: ''
mimetype_name: ''
project_short_description: NBSearch Jupyter Extension
python_name: nbsearch
repository: https://github.com/NII-cloud-operation/nbsearch/
test: true
viewer_name: ''

